steps:
  # Step 1: Download Service Account Key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="terraform-cred" > /workspace/gcp-terraform-keys.json

  # Step 2: Install Terraform and Initialize
  - name: 'hashicorp/terraform:1.5.7'
    id: 'init'
    entrypoint: 'sh'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcp-terraform-keys.json'
    args:
      - '-c'
      - |
        terraform init

  # Step 3: Terraform Plan
  - name: 'hashicorp/terraform:1.5.7'
    id: 'plan'
    entrypoint: 'sh'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcp-terraform-keys.json'
    args:
      - '-c'
      - |
        terraform plan -out=tfplan

  # Step 4: Terraform Apply
  - name: 'hashicorp/terraform:1.5.7'
    id: 'apply'
    entrypoint: 'sh'
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=/workspace/gcp-terraform-keys.json'
    args:
      - '-c'
      - |
        terraform apply -auto-approve tfplan

# Cloud Build Options
options:

  logging: 'CLOUD_LOGGING_ONLY'
service_account: "terraform-deployer@terraform-cloud-build-454706.iam.gserviceaccount.com"
timeout: "1200s"
# projects/525418126086/secrets/terraform-cred