steps:

  # Install Terraform
  - name: 'hashicorp/terraform:1.5.7'
    id: 'init'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init


  # Plan the infrastructure
  - name: 'hashicorp/terraform:1.5.7'
    id: 'plan'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform plan -out=tfplan

  # Apply the changes
  - name: 'hashicorp/terraform:1.5.7'
    id: 'apply'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform apply -auto-approve tfplan

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="Terraform-secret" > /workspace/Terraform-secret.json

# Add logging option
options:
  logging: CLOUD_LOGGING_ONLY   # Use Cloud Logging only

timeout: "1200s"
